config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  resources :posts, except: [:destroy] do
    resources :comments, only: [:create] do
      member do
        post :votes, only: :create
      end
    end

    member do
      post :votes, only: :create
    end
  end

  resources :categories, only: [:show, :new, :create]

  resources :users, only: [:create, :show, :edit, :update]
  get 'register', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, foreign_key: :post_id
  belongs_to :creator, foreign_key: :user_id, class_name: 'User'
  has_many :votes, as: :voteable

  validates :body, presence: true

  def sum_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: :user_id, class_name: 'User'
  has_many :comments, foreign_key: :post_id
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  validates :title, presence: true

  def sum_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, foreign_key: :user_id
  has_many :comments, foreign_key: :user_id
  has_many :votes

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create

  has_secure_password validations: false
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:current_user_id]) if session[:current_user_id]
  end

  def require_user
    if !logged_in?
      flash[:error] = 'Must be logged in to do that.'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))

    if @category.save
      flash[:notice] = 'Category successfully created.'
      redirect_to posts_path
    else
      render 'new'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = 'Comment created successfully.'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def votes
    comment = Comment.find(params[:id])
    vote = Vote.create(voteable: comment, creator: current_user, vote: params[:vote])

    if vote.valid?
      flash[:notice] = "Vote successful!"
    else
      flash[:notice] = "Vote unsuccessful."
    end

    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :votes]
  before_action :require_user, except: [:show, :index]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = 'Post created successfully.'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post updated successfully.'
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def votes
    vote = Vote.create(voteable: @post, vote: params[:vote], creator: current_user)

    if vote.valid?
      flash[:notice] = "Vote successful!"
    else
      flash[:notice] = "Vote unsuccessful."
    end

    redirect_to :back
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      flash[:notice] = "Hello #{user.username}! You are now logged in."
      session[:current_user_id] = user.id
      redirect_to posts_path
    else
      flash[:error] = 'Your input did not match what is in storage.'
      redirect_to login_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    flash[:notice] = 'You are now logged out.'
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:show, :edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'You have registered successfully and are now logged in.'
      session[:current_user_id] = @user.id
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Changes saved."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = 'You do not have permission to do that!'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.start_with?('http://') ? str : 'http://' + str
  end

  def fix_date(datetime)
    datetime.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category' %>

<%= render 'shared/errors', model: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit 'Create Category', class: 'btn'%>
<% end %>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<%= render @category.posts %>

app/views/comments/_comment.html.erb
<div class="clearfix">
  <% if logged_in? %>
    <div class="well span0 text-center">
      <%= link_to votes_post_comment_path(comment.post, comment, vote: true), method: :post do %>
        <i class="icon-arrow-up"></i>
      <% end %>

      <div><%= comment.sum_votes %> Votes</div>

      <%= link_to votes_post_comment_path(comment.post, comment, vote: false), method: :post do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    </div>
  <% end %>

  <div class='well span8'>
    <% user_page ||= false %>
    <% if user_page %>
      <p>
        "<%= comment.body %>"
        <span>on <%= link_to comment.post.title, post_path(comment.post) %></span>
      </p>
    <% else %>
      <p>
        "<%= comment.body %>"
      </p>
    <% end %>
    <small>by: <%= comment.creator.username %></small>
    <small>at: <%= fix_date(comment.created_at) %></small>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>

  <% if !logged_in? %>
    <li>
      <%= link_to 'Register', register_path %>
    </li>
  <% end %>

  <% if logged_in? %>
    <li>
      <%= link_to 'New Post', new_post_path %>
    </li>
  <% else %>
    <li>
      <%= link_to 'Login', login_path %>
    </li>
  <% end %>
</ul>

<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span>
  <% end %>
  <ul class='dropdown-menu'>
    <% Category.all.each do |category| %>
      <li>
        <%= link_to(category.name, category_path(category)) %>
      </li>
    <% end %>
    <% if logged_in? %>
      <li class='divider'></li>
      <li>
        <%= link_to(new_category_path) do %>
          <i class='icon-plus'></i>
          New Category
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if logged_in? %>
  <div class='btn-group nav_item'>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      <%= current_user.username %> <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
        <li>
          <%= link_to 'view profile', user_path(current_user) %>
        </li>
        <li>
          <%= link_to 'edit profile', edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to 'logout', logout_path %>
        </li>

    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', model: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>

  <p>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </p>
  <br>

  <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn')%>
<% end %>

app/views/posts/_post.html.erb
<div class="clearfix">
  <% if logged_in? %>
    <div class="well span0 text-center">
      <%= link_to votes_post_path(post, vote: true), method: :post do %>
        <i class="icon-arrow-up"></i>
      <% end %>

      <div><%= post.sum_votes %> Votes</div>

      <%= link_to votes_post_path(post, vote: false), method: :post do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    </div>
  <% end %>

  <div class='row'>
    <div class='span8 well'>
      <%= render post.categories %>
      <h4><%= link_to post.title, fix_url(post.url) %></h4>
      <p><%= post.description %></p>
      <p>
        <small>by: <%= post.creator.username %></small>
        <small>at:  <%= fix_date(post.created_at) %></small>
      </p>
      <small>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </small>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>

<%= render 'posts/form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts!' %>

<%= render @posts %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'New Post' %>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<%= render @post.categories %>

<div class='pull-right'>
   [<%=link_to 'edit this post', edit_post_path(@post)%>]
</div>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>

<hr>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', model: @comment %>

    <%= f.label :body, 'Leave a comment' %>
    <%= f.text_area :body, cols: 5 %>
    <br>

    <%= f.submit 'Submit Comment', class: 'btn btn-primary' %>
  <% end %>

  <hr>
<% end %>

<h5>Comments</h5>
<%= render @post.comments %>

app/views/shared/_content_title.html.erb
<h1 class='lead'>
  <%= title %>
  <hr>
</h1>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <ul>
  <% model.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', model: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.submit (@user.new_record?) ? 'Register' : 'Update', class: 'btn' %>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Profile' %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'shared/errors', model: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: @user.username %>

<div class='well'>
  <p>
    <b>Username: </b>
    <span><%= @user.username %></span>
  </p>
  <p>
    <b>Time zone: </b>
    <span></span>
  </p>
</div>

<div>
  <p>
    <b><%= @user.username %>'s Activity</b>
  <p>

  <ul class="nav nav-tabs">
    <li class="<%= 'active' if params[:tab].nil? %>">
      <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
    </li>
    <li class="<%= 'active' if params[:tab] %>">
      <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
    </li>
  </ul>

  <% if params[:tab].nil? %>
    <%= render @user.posts %>
  <% elsif params[:tab] == 'comments' %>
    <%= render @user.comments, user_page: true %>
  <% end %>
</div>